CREATE TABLE IF NOT EXISTS `USER` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`)
  ) ENGINE=InnoDB AUTO_INCREMENT=1000000000;

INSERT INTO USER(user_name) VALUES ('stunstunstun')